services:
  - type: web
    name: gamestore-api
    env: node
    rootDir: api
    plan: free
    buildCommand: |
      npm install
      npx prisma migrate deploy
      npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: file:./dev.db
      - key: FRONT_ORIGIN
        sync: false
    postDeployCommand: npm run prisma:seed